// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "dmad1989@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "plain/text"
                ],
                "tags": [
                    "UserURLs"
                ],
                "summary": "Запрос на удаление сокращеных URL",
                "operationId": "deleteUserUrls",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorten": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cut"
                ],
                "summary": "Запрос на сокращение URL",
                "operationId": "cutterJSON",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/jsonobject.Response"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorten/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cut"
                ],
                "summary": "Запрос на сокращение списка URL",
                "operationId": "cutterBatch",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jsonobject.BatchItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/urls": {
            "get": {
                "produces": [
                    "plain/text"
                ],
                "tags": [
                    "UserURLs"
                ],
                "summary": "Все скоращенные URL текущего пользователя",
                "operationId": "userURLs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jsonobject.BatchItem"
                            }
                        }
                    },
                    "204": {
                        "description": "Нет сокращенных URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "plain/text"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Проверка соединения с БД",
                "operationId": "ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{path}": {
            "get": {
                "consumes": [
                    "plain/text"
                ],
                "tags": [
                    "Operate"
                ],
                "summary": "Переход по сокращеному URL",
                "operationId": "redirect",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Сокращенный url",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Переход по сокращенному URL"
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "410": {
                        "description": "url was deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jsonobject.BatchItem": {
            "type": "object",
            "properties": {
                "correlation_id": {
                    "type": "string",
                    "example": "1"
                },
                "original_url": {
                    "description": "URL для сокращения",
                    "type": "string",
                    "example": "http://ya.ru"
                },
                "short_url": {
                    "description": "Сокращенный URL",
                    "type": "string",
                    "example": "http://localhost:8080/rjhsha"
                }
            }
        },
        "jsonobject.Response": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string",
                    "example": "http://localhost:8080/rjhsha"
                }
            }
        }
    },
    "tags": [
        {
            "description": "\"Группа запросов для сокращения URL\"",
            "name": "Cut"
        },
        {
            "description": "\"Группа запросов для работы с URL пользователя\"",
            "name": "UserURLs"
        },
        {
            "description": "\"Группа запросов для работы с сокращенными URL\"",
            "name": "Operate"
        },
        {
            "description": "\"Группа запросов состояния сервиса\"",
            "name": "Info"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "URLCutter API",
	Description:      "Сервис сокращения ссылок.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
