// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: urlcut.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CutterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CutterRequest) Reset() {
	*x = CutterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutterRequest) ProtoMessage() {}

func (x *CutterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutterRequest.ProtoReflect.Descriptor instead.
func (*CutterRequest) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{0}
}

func (x *CutterRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CutterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CutterResponse) Reset() {
	*x = CutterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutterResponse) ProtoMessage() {}

func (x *CutterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutterResponse.ProtoReflect.Descriptor instead.
func (*CutterResponse) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{1}
}

func (x *CutterResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RedirectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorten string `protobuf:"bytes,1,opt,name=shorten,proto3" json:"shorten,omitempty"`
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{2}
}

func (x *RedirectRequest) GetShorten() string {
	if x != nil {
		return x.Shorten
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{3}
}

func (x *RedirectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *URLItem) Reset() {
	*x = URLItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLItem) ProtoMessage() {}

func (x *URLItem) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLItem.ProtoReflect.Descriptor instead.
func (*URLItem) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{4}
}

func (x *URLItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *URLItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type CutterJsonBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch []*URLItem `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *CutterJsonBatchRequest) Reset() {
	*x = CutterJsonBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutterJsonBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutterJsonBatchRequest) ProtoMessage() {}

func (x *CutterJsonBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutterJsonBatchRequest.ProtoReflect.Descriptor instead.
func (*CutterJsonBatchRequest) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{5}
}

func (x *CutterJsonBatchRequest) GetBatch() []*URLItem {
	if x != nil {
		return x.Batch
	}
	return nil
}

type CutterJsonBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch []*URLItem `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *CutterJsonBatchResponse) Reset() {
	*x = CutterJsonBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CutterJsonBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutterJsonBatchResponse) ProtoMessage() {}

func (x *CutterJsonBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutterJsonBatchResponse.ProtoReflect.Descriptor instead.
func (*CutterJsonBatchResponse) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{6}
}

func (x *CutterJsonBatchResponse) GetBatch() []*URLItem {
	if x != nil {
		return x.Batch
	}
	return nil
}

type UserUrlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch []*URLItem `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *UserUrlsResponse) Reset() {
	*x = UserUrlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsResponse) ProtoMessage() {}

func (x *UserUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsResponse.ProtoReflect.Descriptor instead.
func (*UserUrlsResponse) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{7}
}

func (x *UserUrlsResponse) GetBatch() []*URLItem {
	if x != nil {
		return x.Batch
	}
	return nil
}

type DeleteUserUrlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteUserUrlsRequest) Reset() {
	*x = DeleteUserUrlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserUrlsRequest) ProtoMessage() {}

func (x *DeleteUserUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserUrlsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserUrlsRequest) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserUrlsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int32 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int32 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlcut_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlcut_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_urlcut_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_urlcut_proto protoreflect.FileDescriptor

var file_urlcut_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0d, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x22, 0x24, 0x0a,
	0x10, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x70, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x3f, 0x0a, 0x16, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x4a,
	0x73, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x55, 0x52, 0x4c, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x22, 0x40, 0x0a, 0x17, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x55, 0x52, 0x4c, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x22, 0x39, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x72,
	0x6c, 0x63, 0x75, 0x74, 0x2e, 0x55, 0x52, 0x4c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x22, 0x29, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x39,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x75,
	0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0x89, 0x04, 0x0a, 0x06, 0x55, 0x72,
	0x6c, 0x43, 0x75, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x4a, 0x73,
	0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x43, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x72, 0x6c, 0x63,
	0x75, 0x74, 0x2e, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x06, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x75, 0x72,
	0x6c, 0x63, 0x75, 0x74, 0x2e, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x43, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e,
	0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x75, 0x74, 0x74, 0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x1e, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x43, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x43, 0x75,
	0x74, 0x74, 0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x75, 0x72, 0x6c, 0x63,
	0x75, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15,
	0x2e, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x75, 0x72, 0x6c, 0x63, 0x75, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_urlcut_proto_rawDescOnce sync.Once
	file_urlcut_proto_rawDescData = file_urlcut_proto_rawDesc
)

func file_urlcut_proto_rawDescGZIP() []byte {
	file_urlcut_proto_rawDescOnce.Do(func() {
		file_urlcut_proto_rawDescData = protoimpl.X.CompressGZIP(file_urlcut_proto_rawDescData)
	})
	return file_urlcut_proto_rawDescData
}

var file_urlcut_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_urlcut_proto_goTypes = []interface{}{
	(*CutterRequest)(nil),           // 0: urlcut.CutterRequest
	(*CutterResponse)(nil),          // 1: urlcut.CutterResponse
	(*RedirectRequest)(nil),         // 2: urlcut.RedirectRequest
	(*RedirectResponse)(nil),        // 3: urlcut.RedirectResponse
	(*URLItem)(nil),                 // 4: urlcut.URLItem
	(*CutterJsonBatchRequest)(nil),  // 5: urlcut.CutterJsonBatchRequest
	(*CutterJsonBatchResponse)(nil), // 6: urlcut.CutterJsonBatchResponse
	(*UserUrlsResponse)(nil),        // 7: urlcut.UserUrlsResponse
	(*DeleteUserUrlsRequest)(nil),   // 8: urlcut.DeleteUserUrlsRequest
	(*StatsResponse)(nil),           // 9: urlcut.StatsResponse
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_urlcut_proto_depIdxs = []int32{
	4,  // 0: urlcut.CutterJsonBatchRequest.batch:type_name -> urlcut.URLItem
	4,  // 1: urlcut.CutterJsonBatchResponse.batch:type_name -> urlcut.URLItem
	4,  // 2: urlcut.UserUrlsResponse.batch:type_name -> urlcut.URLItem
	0,  // 3: urlcut.UrlCut.CutterJson:input_type -> urlcut.CutterRequest
	0,  // 4: urlcut.UrlCut.Cutter:input_type -> urlcut.CutterRequest
	2,  // 5: urlcut.UrlCut.Redirect:input_type -> urlcut.RedirectRequest
	10, // 6: urlcut.UrlCut.Ping:input_type -> google.protobuf.Empty
	5,  // 7: urlcut.UrlCut.CutterJsonBatch:input_type -> urlcut.CutterJsonBatchRequest
	10, // 8: urlcut.UrlCut.UserUrls:input_type -> google.protobuf.Empty
	8,  // 9: urlcut.UrlCut.DeleteUsersUrls:input_type -> urlcut.DeleteUserUrlsRequest
	10, // 10: urlcut.UrlCut.Stats:input_type -> google.protobuf.Empty
	1,  // 11: urlcut.UrlCut.CutterJson:output_type -> urlcut.CutterResponse
	1,  // 12: urlcut.UrlCut.Cutter:output_type -> urlcut.CutterResponse
	3,  // 13: urlcut.UrlCut.Redirect:output_type -> urlcut.RedirectResponse
	10, // 14: urlcut.UrlCut.Ping:output_type -> google.protobuf.Empty
	6,  // 15: urlcut.UrlCut.CutterJsonBatch:output_type -> urlcut.CutterJsonBatchResponse
	7,  // 16: urlcut.UrlCut.UserUrls:output_type -> urlcut.UserUrlsResponse
	10, // 17: urlcut.UrlCut.DeleteUsersUrls:output_type -> google.protobuf.Empty
	9,  // 18: urlcut.UrlCut.Stats:output_type -> urlcut.StatsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_urlcut_proto_init() }
func file_urlcut_proto_init() {
	if File_urlcut_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_urlcut_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedirectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedirectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutterJsonBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CutterJsonBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUrlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserUrlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlcut_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_urlcut_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlcut_proto_goTypes,
		DependencyIndexes: file_urlcut_proto_depIdxs,
		MessageInfos:      file_urlcut_proto_msgTypes,
	}.Build()
	File_urlcut_proto = out.File
	file_urlcut_proto_rawDesc = nil
	file_urlcut_proto_goTypes = nil
	file_urlcut_proto_depIdxs = nil
}
